### ISSUE TITLE
👍This is a great project!!

### ISSUE THREAD

**Issue by Frederic-Zhou** [babbleio/babble#155]
It's great library and hope that the author will continue to maintain it
👍👍👍👍👍

**Comment by arrivets** [comment]
Thanks for the kind words!

**Comment by Frederic-Zhou** [comment]
I have a question. Is the algorithm used by babble protected by the original Hashgraph patent or not？

**Comment by arrivets** [comment]
Sorry for the late reply. No I don't think it is. But don't take my word for it.

**Comment by Frederic-Zhou** [comment]
Thanks for your reply!!
👍
